// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_application_final_project/Modells/Notiz.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NotizAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NotizAdapter());
  }
}
